[package]
name = "snowflake-id-generator"
version = "0.2.0"
edition = "2024"
description = "Simple implementation of snowflake id generator"
license = "Unlicense"

[dependencies]
tokio = { version = "1.47.1", features = ["sync", "rt", "macros"] }