[package]
name = "snowflake-id-generator"
version = "0.2.0"
edition = "2024"
description = "Simple snowflake id implementation"
license = "Unlicense"
repository = "https://github.com/Axoneo/snowflake-id-rs"

[dependencies]
tokio = { version = "1.47.1", features = ["sync", "rt", "macros"] }